Update release note format
simple-icons/release-action pull request #82
Opened 2024-02-07 14:26 UTC by LitoMore

I updated the release note format to similar to [`npm/cli` release note](https://github.com/npm/cli/releases/tag/v10.4.0).

The benefit is the `Contributors` section in the release note.

I also removed the `core.debug(file)`. It's too long and super hard to read. We can simply use the GitHub REST API to check specific PR response. Or use our `npm run preview` script for debugging.

2024-02-07 14:33 UTC, adamrusted commented on test/create.test.js
Is it worth having more than one maintainer named here - just to validate?

2024-02-07 14:42 UTC, LitoMore commented on test/create.test.js
GitHub REST API does not support co-author field.

In the meantime, I prefer to close a stale PR and create new one instead.

However, You can still update the release note in its created release PR.

2024-02-07 19:53 UTC, adamrusted commented on test/create.test.js
I meant having more than one author in our test script, to prove that it doesn't mix up PR creators.

2024-02-09 00:49 UTC, mondeja approved these changes
Looks good to me though I like the @adamrusted's suggestion.

2024-02-09 08:25 UTC, adamrusted requested changes
Varying the maintainer names used, to properly demonstrate functionality works.

2024-02-09 08:25 UTC, adamrusted commented on __mocks__/@actions/github.js
> +    user: { login: 'LitoMore' },
Added a variety of maintainer names to the mock data.
To be applied along with the update to tests, also listed.

```suggestion
    number: 500,
    merged_at: null,
    base: { ref: 'develop' },
    user: { login: 'adamrusted' },
  },
  {
    //  1: PR that adds a file
    title: '501',
    number: 501,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'LitoMore' },
  },
  {
    //  2: PR that modifies an SVG
    title: '502',
    number: 502,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'mondeja' },
  },
  {
    //  3: PR that was merged before the previous release
    title: '498',
    number: 498,
    merged_at: '2011-01-01T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'PeterShaggyNoble' },
  },
  {
    //  4: PR that modifies one icon's color
    title: '503',
    number: 503,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'service-paradis' },
  },
  {
    //  5: PR that modifies one icon's source
    title: '504',
    number: 504,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'fbernhart' },
  },
  {
    //  6: PR that modifies one icon's color and source
    title: '505',
    number: 505,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'adamrusted' },
  },
  {
    //  7: PR that modifies an SVG and modifies that icon's color
    title: '506',
    number: 506,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'LitoMore' },
  },
  {
    //  8: PR that modifies an SVG and modifies that icon's source
    title: '507',
    number: 507,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'mondeja' },
  },
  {
    //  9: PR that modifies an SVG and modifies that icon's color and source
    title: '508',
    number: 508,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'PeterShaggyNoble' },
  },
  {
    // 10: PR that adds an SVG and modifies another icon's color and source
    title: '509',
    number: 509,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'service-paradis' },
  },
  {
    // 11: PR that adds an SVG and modifies another SVG
    title: '510',
    number: 510,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'fbernhart' },
  },
  {
    // 12: PR that changes the data file but no metadata
    title: '511',
    number: 511,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'adamrusted' },
  },
  {
    // 13: PR that adds a brand with a lowercased name
    title: '512',
    number: 512,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'LitoMore' },
  },
  {
    // 14: PR that adds ACM (which should be listed before the lowercased brand)
    title: '513',
    number: 513,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'mondeja' },
  },
  {
    // 15: PR that adds a brand with an accented name
    title: '514',
    number: 514,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'PeterShaggyNoble' },
  },
  {
    // 16: PR that removes an icon
    title: '515',
    number: 515,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'develop' },
    user: { login: 'service-paradis' },
  },
  {
    // Skipped release
    title: '[skip] Skip this one',
    number: 516,
    merged_at: '2011-01-26T19:01:12Z',
    base: { ref: 'master' },
    user: { login: 'fbernhart' },
  },
  {
    // Previous release
    title: 'Release',
    number: 499,
    merged_at: '2011-01-02T19:01:12Z',
    base: { ref: 'master' },
    user: { login: 'LitoMore' },
```

2024-02-09 08:25 UTC, adamrusted commented on test/create.test.js
> +- WordPress (#510) (@LitoMore)
```suggestion
- ACM (#513) (@mondeja)
- bar (#512) (@LitoMore)
- Foo (#501) (@LitoMore)
- Jest (#509) (@service-paradis)
- Pokémon (#514) (@PeterShaggyNoble)
- WordPress (#510) (@fbernhart)
```

2024-02-09 08:25 UTC, adamrusted commented on test/create.test.js
> +- Postman (#506) (@LitoMore)
```suggestion
- 1Password (#503) (@service-paradis)
- Abstract (#509) (@service-paradis)
- AddThis (#508) (@PeterShaggyNoble)
- Adobe (#504) (@fbernhart)
- Feedly (#502) (@mondeja)
- Intel (#507) (@mondeja)
- Mozilla (#505) (@adamrusted)
- Opera (#510) (@fbernhart)
- Postman (#506) (@LitoMore)
```

2024-02-09 08:25 UTC, adamrusted commented on test/create.test.js
> +- Foobar (#515) (@LitoMore)
```suggestion
- Foobar (#515) (@service-paradis)
```

2024-02-10 09:17 UTC, merged